const companySymbols = {
  tesla: "TSLA",
  apple: "AAPL",
  microsoft: "MSFT",
  google: "GOOGL",
  alphabet: "GOOGL",
  amazon: "AMZN",
  meta: "META",
  facebook: "META",
  netflix: "NFLX",
  nvidia: "NVDA",
  amd: "AMD",
  intel: "INTC",
  oracle: "ORCL",
  adobe: "ADBE",
  salesforce: "CRM",
  uber: "UBER",
  paypal: "PYPL",
  spotify: "SPOT",
  disney: "DIS",
  cocacola: "KO",
  pepsi: "PEP",
  nike: "NKE",
  walmart: "WMT",
  costco: "COST",
  visa: "V",
  mastercard: "MA",
  jpmorgan: "JPM",
  goldmansachs: "GS",
  boeing: "BA",
  ford: "F",
  generalmotors: "GM"
};

export default companySymbols;